# Generated by Django 5.2.6 on 2025-10-01 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPokemon',
            fields=[
                ('idtipopokemon', models.AutoField(db_column='IDTipoPokemon', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='Descricao', max_length=40)),
            ],
            options={
                'db_table': 'TipoPokemon',
            },
        ),
        migrations.CreateModel(
            name='PokemonUsuario',
            fields=[
                ('idpokemonusuario', models.AutoField(db_column='IDPokemonUsuario', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='Codigo', max_length=50)),
                ('imagemurl', models.CharField(db_column='ImagemUrl', max_length=255)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('grupobatalha', models.BooleanField(db_column='GrupoBatalha', default=False)),
                ('favorito', models.BooleanField(db_column='Favorito', default=False)),
                ('usuario', models.ForeignKey(db_column='IDUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to=settings.AUTH_USER_MODEL)),
                ('tipopokemon', models.ManyToManyField(db_table='PokemonUsuario_Tipos', related_name='pokemons', to='pokemon.tipopokemon')),
            ],
            options={
                'db_table': 'PokemonUsuario',
            },
        ),
    ]
